// languages.js

const languages = [
    { code: "auto", name: "Auto Detect", native: "Auto Detect" },
    { code: "en", name: "English", native: "English" },
    { code: "hi", name: "Hindi", native: "हिन्दी" },
    { code: "es", name: "Spanish", native: "Español" },
    { code: "fr", name: "French", native: "Français" },
    { code: "de", name: "German", native: "Deutsch" },
    { code: "zh-CN", name: "Chinese (Simplified)", native: "简体中文" },
    { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
    { code: "ja", name: "Japanese", native: "日本語" },
    { code: "ko", name: "Korean", native: "한국어" },
    { code: "ar", name: "Arabic", native: "العربية" },
    { code: "pt", name: "Portuguese", native: "Português" },
    { code: "ru", name: "Russian", native: "Русский" },
    { code: "it", name: "Italian", native: "Italiano" },
    { code: "bn", name: "Bengali", native: "বাংলা" },
    { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
    { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
    { code: "ta", name: "Tamil", native: "தமிழ்" },
    { code: "te", name: "Telugu", native: "తెలుగు" },
    { code: "ml", name: "Malayalam", native: "മലയാളം" },
    { code: "mr", name: "Marathi", native: "मराठी" },
    { code: "ur", name: "Urdu", native: "اردو" },
    { code: "tr", name: "Turkish", native: "Türkçe" },
    { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
    { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
    { code: "th", name: "Thai", native: "ไทย" },
    { code: "sw", name: "Swahili", native: "Kiswahili" },
    { code: "nl", name: "Dutch", native: "Nederlands" },
    { code: "sv", name: "Swedish", native: "Svenska" },
    { code: "fi", name: "Finnish", native: "Suomi" },
    { code: "no", name: "Norwegian", native: "Norsk" },
    { code: "da", name: "Danish", native: "Dansk" },
    { code: "el", name: "Greek", native: "Ελληνικά" },
    { code: "he", name: "Hebrew", native: "עברית" },
    { code: "pl", name: "Polish", native: "Polski" },
    { code: "uk", name: "Ukrainian", native: "Українська" },
    { code: "hu", name: "Hungarian", native: "Magyar" },
    { code: "cs", name: "Czech", native: "Čeština" },
    { code: "ro", name: "Romanian", native: "Română" },
    { code: "bg", name: "Bulgarian", native: "Български" },
    { code: "sk", name: "Slovak", native: "Slovenčina" },
    { code: "hr", name: "Croatian", native: "Hrvatski" },
    { code: "sr", name: "Serbian", native: "Српски" },
    { code: "lt", name: "Lithuanian", native: "Lietuvių" },
    { code: "lv", name: "Latvian", native: "Latviešu" },
    { code: "et", name: "Estonian", native: "Eesti" },
    { code: "sl", name: "Slovenian", native: "Slovenščina" },
    { code: "fa", name: "Persian", native: "فارسی" },
    { code: "am", name: "Amharic", native: "አማርኛ" },
    { code: "tl", name: "Tagalog", native: "Tagalog" },
    { code: "so", name: "Somali", native: "Soomaali" },
    { code: "zu", name: "Zulu", native: "IsiZulu" },
    { code: "xh", name: "Xhosa", native: "IsiXhosa" },
    { code: "af", name: "Afrikaans", native: "Afrikaans" },
  ];
  
  